from django.urls import path
from . import views


urlpatterns = [
    path('departements/', views.get_departements, name='get_departements'),
    path('departements/create/', views.create_departement, name='create_departement'),
    path('departements/update/<int:id>/', views.update_departement, name='update_departement'),
    path('departements/delete/<int:id>/', views.delete_departement, name='delete_departement'),
    path('departements/change-chef/<int:id>/', views.change_chef_departement, name='change_chef_departement'),
    path('departements/<int:id>/filieres/', views.get_departement_filiers, name='get_departement_filiers'),
    path('departements/<int:id>/filieres/create/', views.create_filiere_in_departement, name='create_filiere_in_departement'),
    path('filieres/', views.get_all_filieres, name='get_all_filieres'),
    path('departement/filiere/<int:id>/assign-chef/', views.assign_chef_filiere, name='assign_chef_filiere'),
    path('filieres/update/<int:id>/', views.update_filiere, name='update_filiere'),
    path('filieres/delete/<int:id>/', views.delete_filiere, name='delete_filiere'),
    path('filieres/<int:id>/groupes/', views.get_filiere_groupes, name='get_filiere_groupes'),
    path('groupes/', views.list_groups, name='list_groups'),
    path('groupes/create/', views.create_groups, name='create_groups'),
    path('groupes/<int:id>/', views.group_detail, name='group_detail'),
    path('groupes/update/<int:id>/', views.update_group, name='update_group'),
    path('groupes/delete/<int:id>/', views.delete_group, name='delete_group'),
    path('salles/', views.list_salles, name='list_salles'),
    path('salles/create/', views.create_salle, name='create_salle'),
    path('salles/<int:id>/', views.get_salle_detail, name='get_salle_detail'),
    path('salles/update/<int:id>/', views.update_salle, name='update_salle'),
    path('salles/delete/<int:id>/', views.delete_salle, name='delete_salle'),
    path('modules/', views.get_modules, name='get_modules'),
    path('modules/create/', views.create_module, name='create_module'),
    path('modules/<int:id>/', views.get_module_detail, name='get_module_detail'),
    path('modules/update/<int:id>/', views.update_module, name='update_module'),
    path('modules/delete/<int:id>/', views.delete_module, name='delete_module'),
    path('modules/my/', views.my_modules, name='my_modules'),
    path('modules/<int:id>/assign-prof/', views.assign_professor_to_module, name='assign_professor_to_module'),
    path('departements/<int:id>/suivi-pedagogique/', views.departement_suivi_pedagogique, name='departement_suivi_pedagogique'),
    path('departements/<int:id>/stats/', views.departement_stats, name='departement_stats'),
    path('filieres/<int:id>/stats/', views.filieres_stats, name='filieres_stats'),
    path('professeurs/mes-etudiants/', views.get_professor_students, name='get_professor_students'),
]
